const chapters = {
    1: "ask fad alas asks shad lads flags flask glass jag fag fall hash glad sags galls halls salad jak has jags gaff hall dash flash slash flasks lad sad lash adds gall gash shall lakhs dhalls ask fad alas asks shad lads flags flask glass jag fag fall hash glad sags galls halls salad jak has jags gaff hall dash flash slash flasks lad sad lash adds gall gash shall lakhs dhall sask fad alas asks shad lads flags flask glass jag fag fall hash glad sags galls halls salad jak has jags gaff hall dash flash slash flasks lad sad lash adds gall gash shall lakhs dhalls",
    2: "fish kodak ahead larks quail apples reader flukes fiddlefish kodak ahead larks quail apples reader flukes fiddle dead rails sales agile isles should liquid shower saddle idols jaded sails filed legal folder sledge squall larger grade jails lakes roses rupee squeal fields lulled dislike apple dirks lease equip skill easels dollar poorer require asked forks hedge would grass jokers jailer equals refresh fails usual liked walks peaks orders follow drawls defiles fish kodak ahead larks quail apples reader flukes fiddle dead rails sales agile isles should liquid shower saddle idols jaded sails filed legal folder sledge squall larger grade jails lakes roses rupee squeal fields lulled dislike apple dirks lease equip skill easels dollar poorer require asked forks hedge would grass jokers jailer equals refresh fails usual liked walks peaks orders follow drawls defiles",
    3: "lawyers streaks shipped hillside herewith proposals typewriter shekels forward desired loophole jugglers strapples yesterday hatless figures prepare feathery freehold struggles kirkwall thought thyself treated assessed prepared territory laughter quarter yodlers youthful although supplies guileless waggish freight further ploughes shippers slightly telegraph without dutiful pleased goodwill tortuous property addressed powerfully laughed kettles whiskers thorough repeated flashlight etiquette petrols regular equipped lilliput lawyers streaks shipped hillside herewith proposals typewriter shekels forward desired loophole jugglers strapples yesterday hatless figures prepare feathery freehold struggles kirkwall thought thyself treated assessed prepared territory laughter quarter yodlers youthful although supplies guileless waggish freight further ploughes shippers slightly telegraph without dutiful pleased goodwill tortuous property addressed powerfully laughed kettles whiskers thorough repeated flashlight etiquette petrols regular equipped lilliput",
    4: "amazed journal gambols pickling vineyard grizzled except jackets fixture austrian appeared frequent logical student spacing movement joyfully premises sixfold succeed western examined accuracy fortress daybook lecture neither vexation quantity executor kindled general private practice question deduction jingled amulets service produces requires judicious jumbled arrival relative provoked starting materials swivels fizzed possible somewhat cylinder assessment violets regaled becoming gracious thousand appearance amazed journal gambols pickling vineyard grizzled except jackets fixture austrian appeared frequent logical student spacing movement joyfully premises sixfold succeed western examined accuracy fortress daybook lecture neither vexation quantity executor kindled general private practice question deduction jingled amulets service produces requires judicious jumbled arrival relative provoked starting materials swivels fizzed possible somewhat cylinder assessment violets regaled becoming gracious thousand appearanceamazed journal gambols pickling vineyard grizzled except jackets fixture austrian appeared frequent logical student spacing movement joyfully premises sixfold succeed western examined accuracy fortress daybook lecture neither vexation quantity executor kindled general private practice question deduction jingled amulets service produces requires judicious jumbled arrival relative provoked starting materials swivels fizzed possible somewhat cylinder assessment violets regaled becoming gracious thousand appearance",
    5: "points children clockwork remittance punctuation constitution common frequent requisite attractive distinction arrangements sinful ambition novelties yardsticks environment approximately summer umbrella answering foundation explanation distinguished behalf armature regarding guaranteed association ornamentation exhibit relieved exceeding sufference competition peculiarities thunder citizens abundance atmosphere transmitted specification maximum commonly apparatus partition questionless investigations adopting pamphlets accompany communicate installation circumstances points children clockwork remittance punctuation constitution common frequent requisite attractive distinction arrangements sinful ambition novelties yardsticks environment approximately summer umbrella answering foundation explanation distinguished behalf armature regarding guaranteed association ornamentation exhibit relieved exceeding sufference competition peculiarities thunder citizens abundance atmosphere transmitted specification maximum commonly apparatus partition questionless investigations adopting pamphlets accompany communicate installation circumstances",
    6: "876 1973 1847 23,846 10,746 1,37,946 424 5567 8563 11,200 11,140 7,13,345 537 2136 2746 23,476 23,450 14,06,786 948 4520 7361 15,409 27,763 18,76,432 473 6286 3950 78,796 86,521 20,54,362 572 9567 925,489 95,362 31,98,453",
    7: "July Canada Gandhiji Minister Registered Sita Kerala Varghese Delivery Swamimalai Leela Bezawada Strictly Tamilnadu Departure March Janatha Govindan Secretary Concurrent Raman Express Exercise Conferred Notification Guntur Prakash Schedule Government Confidential Kannan October Calcutta Kumbakonam Superintendent",
    8: "Lost time is never regained. Get up early and do your work. To-day's youth and to-morrow's old. Age is virtue when wisdom is with it. Measure your word before it goes out of you. Children are innocent and should be guided rightly. Our Land had great sages who knew the eternal truth.  ",
    9: "Men live by deeds and not by years. God helps those who help themselves. Honest work always brings its reward. A man without character should not be trusted. Rude language speaks ill of the man who uses it. Never lose courage when faced with difficulties. It is easier to ask questions than to answer them. Pandit Nehru always devoted himself to public affairs. It is essential to use the touch method. The correct degree of touch is an important factor. The touch should be neither too heavy nor too light. High speed is within the capacity of every typist. Astronomy is the oldest science. Young men have a right to be happy. A petty man refuses to admit defeat. Man is mortal, but his spirit is immortal. Sivaji fought to keep the real spirit of India alive. Tilak was a great Patriot and also a brilliant scholar.",
    10: "Pack my box with five dozen liquor jugs. A quick brown fox slowly jumped over the lazy dog. Petty quiz badly vexes chuffy worker hungry James. Five prizes were quickly distributed by the judge to examinees. Gay men with extra pluck and zeal would often have quiet jobs. Black market fugitive should be quickly expelled with zeal by any just society. Quiet Parsi fugitives in India extolled justly their most watched book Zend Avesta. May we have Jack Squires fix the big lamps for Andy Ziegler. Ramji worked with zeal and vigor to protect his quietful subjects excellently well. Handy Jack quixotic laziness may grow to be far expensive.",

    11: "The French Revolution was in 1789. The partition of India affected more than fifty percent of our people. I gave him a cheque for Rs 100 only. Rice was sold at Rs 325 per bag. Every Indian said that partition is bad. Messrs Raman and Company Limited were great toy makers. Raman got three fourth and Krishna one fourth of their shares. The cost of a good clock is two pounds. Rajan and Kumaran sailed on second February nineteen sixty for England. Have you seen my brother in law Ramachary. Received five sets of typists tables and chairs. Leave two spaces after comma.",
    12: "ask fad alas asks shad",
    13: "asdf jkl; asdf ;lkjas dj fk sl ad fj sadf jkl; fdsa ;lkj ask dad fall lad flask sad all dad asjk df;l asdf jkl; a s d f j k l ; fdsa jkl; asdf ;lkj lad sad flask dad asdf asjk jkl; fdsa fall ask dad sad asdj fl;k sadf jkl; dad fall ask lad jkl; asdf lkj; fdsa ask fall sad dad asdf jkl; sadf ;lkj asdf jkl; asdf ;lkjas dj fk sl ad fj sadf jkl; fdsa ;lkj ask dad fall lad flask sad all dad asjk df;l asdf jkl; a s d f j k l ; fdsa jkl; asdf ;lkj lad sad flask dad asdf asjk jkl; fdsa fall ask dad sad asdj fl;k sadf jkl; dad fall ask lad jkl; asdf lkj; fdsa ask fall sad dad asdf jkl; sadf ;lkj",


};