const chapters = {
    1: "ask fad alas asks shad lads flags flask glass jag fag fall hash glad sags galls halls salad jak has jags gaff hall dash flash slash flasks lad sad lash adds gall gash shall lakhs dhalls ask fad alas asks shad lads flags flask glass jag fag fall hash glad sags galls halls salad jak has jags gaff hall dash flash slash flasks lad sad lash adds gall gash shall lakhs dhall sask fad alas asks shad lads flags flask glass jag fag fall hash glad sags galls halls salad jak has jags gaff hall dash flash slash flasks lad sad lash adds gall gash shall lakhs dhalls",
    2: "fish kodak ahead larks quail apples reader flukes fiddlefish kodak ahead larks quail apples reader flukes fiddle dead rails sales agile isles should liquid shower saddle idols jaded sails filed legal folder sledge squall larger grade jails lakes roses rupee squeal fields lulled dislike apple dirks lease equip skill easels dollar poorer require asked forks hedge would grass jokers jailer equals refresh fails usual liked walks peaks orders follow drawls defiles fish kodak ahead larks quail apples reader flukes fiddle dead rails sales agile isles should liquid shower saddle idols jaded sails filed legal folder sledge squall larger grade jails lakes roses rupee squeal fields lulled dislike apple dirks lease equip skill easels dollar poorer require asked forks hedge would grass jokers jailer equals refresh fails usual liked walks peaks orders follow drawls defiles",
    3: "lawyers streaks shipped hillside herewith proposals typewriter shekels forward desired loophole jugglers strapples yesterday hatless figures prepare feathery freehold struggles kirkwall thought thyself treated assessed prepared territory laughter quarter yodlers youthful although supplies guileless waggish freight further ploughes shippers slightly telegraph without dutiful pleased goodwill tortuous property addressed powerfully laughed kettles whiskers thorough repeated flashlight etiquette petrols regular equipped lilliput lawyers streaks shipped hillside herewith proposals typewriter shekels forward desired loophole jugglers strapples yesterday hatless figures prepare feathery freehold struggles kirkwall thought thyself treated assessed prepared territory laughter quarter yodlers youthful although supplies guileless waggish freight further ploughes shippers slightly telegraph without dutiful pleased goodwill tortuous property addressed powerfully laughed kettles whiskers thorough repeated flashlight etiquette petrols regular equipped lilliput",
    4: "amazed journal gambols pickling vineyard grizzled except jackets fixture austrian appeared frequent logical student spacing movement joyfully premises sixfold succeed western examined accuracy fortress daybook lecture neither vexation quantity executor kindled general private practice question deduction jingled amulets service produces requires judicious jumbled arrival relative provoked starting materials swivels fizzed possible somewhat cylinder assessment violets regaled becoming gracious thousand appearance amazed journal gambols pickling vineyard grizzled except jackets fixture austrian appeared frequent logical student spacing movement joyfully premises sixfold succeed western examined accuracy fortress daybook lecture neither vexation quantity executor kindled general private practice question deduction jingled amulets service produces requires judicious jumbled arrival relative provoked starting materials swivels fizzed possible somewhat cylinder assessment violets regaled becoming gracious thousand appearanceamazed journal gambols pickling vineyard grizzled except jackets fixture austrian appeared frequent logical student spacing movement joyfully premises sixfold succeed western examined accuracy fortress daybook lecture neither vexation quantity executor kindled general private practice question deduction jingled amulets service produces requires judicious jumbled arrival relative provoked starting materials swivels fizzed possible somewhat cylinder assessment violets regaled becoming gracious thousand appearance",
    5: "points children clockwork remittance punctuation constitution common frequent requisite attractive distinction arrangements sinful ambition novelties yardsticks environment approximately summer umbrella answering foundation explanation distinguished behalf armature regarding guaranteed association ornamentation exhibit relieved exceeding sufference competition peculiarities thunder citizens abundance atmosphere transmitted specification maximum commonly apparatus partition questionless investigations adopting pamphlets accompany communicate installation circumstances points children clockwork remittance punctuation constitution common frequent requisite attractive distinction arrangements sinful ambition novelties yardsticks environment approximately summer umbrella answering foundation explanation distinguished behalf armature regarding guaranteed association ornamentation exhibit relieved exceeding sufference competition peculiarities thunder citizens abundance atmosphere transmitted specification maximum commonly apparatus partition questionless investigations adopting pamphlets accompany communicate installation circumstances",
    6: "876 1973 1847 23,846 10,746 1,37,946 424 5567 8563 11,200 11,140 7,13,345 537 2136 2746 23,476 23,450 14,06,786 948 4520 7361 15,409 27,763 18,76,432 473 6286 3950 78,796 86,521 20,54,362 572 9567 925,489 95,362 31,98,453",
    7: "July Canada Gandhiji Minister Registered Sita Kerala Varghese Delivery Swamimalai Leela Bezawada Strictly Tamilnadu Departure March Janatha Govindan Secretary Concurrent Raman Express Exercise Conferred Notification Guntur Prakash Schedule Government Confidential Kannan October Calcutta Kumbakonam Superintendent",
    8: "Lost time is never regained. Get up early and do your work. To-day's youth and to-morrow's old. Age is virtue when wisdom is with it. Measure your word before it goes out of you. Children are innocent and should be guided rightly. Our Land had great sages who knew the eternal truth.  ",
    9: "Men live by deeds and not by years. God helps those who help themselves. Honest work always brings its reward. A man without character should not be trusted. Rude language speaks ill of the man who uses it. Never lose courage when faced with difficulties. It is easier to ask questions than to answer them. Pandit Nehru always devoted himself to public affairs. It is essential to use the touch method. The correct degree of touch is an important factor. The touch should be neither too heavy nor too light. High speed is within the capacity of every typist. Astronomy is the oldest science. Young men have a right to be happy. A petty man refuses to admit defeat. Man is mortal, but his spirit is immortal. Sivaji fought to keep the real spirit of India alive. Tilak was a great Patriot and also a brilliant scholar.",
    10: "Pack my box with five dozen liquor jugs. A quick brown fox slowly jumped over the lazy dog. Petty quiz badly vexes chuffy worker hungry James. Five prizes were quickly distributed by the judge to examinees. Gay men with extra pluck and zeal would often have quiet jobs. Black market fugitive should be quickly expelled with zeal by any just society. Quiet Parsi fugitives in India extolled justly their most watched book Zend Avesta. May we have Jack Squires fix the big lamps for Andy Ziegler. Ramji worked with zeal and vigor to protect his quietful subjects excellently well. Handy Jack quixotic laziness may grow to be far expensive.",

    11: "The French Revolution was in 1789. The partition of India affected more than fifty percent of our people. I gave him a cheque for Rs 100 only. Rice was sold at Rs 325 per bag. Every Indian said that partition is bad. Messrs Raman and Company Limited were great toy makers. Raman got three fourth and Krishna one fourth of their shares. The cost of a good clock is two pounds. Rajan and Kumaran sailed on second February nineteen sixty for England. Have you seen my brother in law Ramachary. Received five sets of typists tables and chairs. Leave two spaces after comma.",
    12: "ask fad alas asks shad",
    13: "asdf jkl; asdf ;lkjas dj fk sl ad fj sadf jkl; fdsa ;lkj ask dad fall lad flask sad all dad asjk df;l asdf jkl; a s d f j k l ; fdsa jkl; asdf ;lkj lad sad flask dad asdf asjk jkl; fdsa fall ask dad sad asdj fl;k sadf jkl; dad fall ask lad jkl; asdf lkj; fdsa ask fall sad dad asdf jkl; sadf ;lkj asdf jkl; asdf ;lkjas dj fk sl ad fj sadf jkl; fdsa ;lkj ask dad fall lad flask sad all dad asjk df;l asdf jkl; a s d f j k l ; fdsa jkl; asdf ;lkj lad sad flask dad asdf asjk jkl; fdsa fall ask dad sad asdj fl;k sadf jkl; dad fall ask lad jkl; asdf lkj; fdsa ask fall sad dad asdf jkl; sadf ;lkj",
    1: "पर कर तक पट टक चट कप पच रट टप पर कर तक पट टक चट कप पच रट टप कर पट टक चट कप पच रट टप पर तक कर पट टक चट कप पच रट टप पर तक पर कर तक पट टक चट कप पच रट टप पर कर तक पट टक चट कप पच रट टप कर पट टक चट कप पच रट टप पर तक कर पट टक चट कप पच रट टप पर तक पर कर तक पट टक चट कप पच रट टप पर कर तक पट टक चट कप पच रट टप कर पट टक चट कप पच रट टप पर तक कर पट टक चट कप पच रट टप पर तक पर कर तक पट टक चट कप पच रट टप पर कर तक पट टक चट कप पच रट टप कर पट टक चट कप पच रट टप पर तक कर पट टक चट कप पच रट टप पर तक",
    2: "पिर किर तिर चित चिप टिप तिक पिट चिर पुर कुर तुर चुर टुक पुट कुट तुक चुक रुक पुट कुट तुक चुक रुक पुर पर कर तक पट टक चट कप पच रट टप कर पट टक चट कप पच रट टप पर तक कुर तुर चुर पिर किर तिर चित चिप टिप तिक पिट चिर पुर कुर तुर चुर टुक पुट कुट तुक चुक रुक पुट कुट तुक चुक रुक पुर कुर तुर चुर पिर किर तिर चित चिप टिप तिक पिट चिर पुर कुर तुर चुर टुक पुट कुट तुक चुक रुक पुट कुट तुक चुक रुक पुर कुर तुर चुर पर कर तक पट टक चट कप पच रट टप कर पट टक चट कप पच रट टप पर तक",
    3: "पे के ते रे चे टे पेच केत रेत चेत पो को तो रो चो टो रोक कोट चोर पोत पो तो को रो चो टो कोट रोक चोर पोत पिरो किर तिको चितर पुटक कुरत चुपे रुकट पिरत पिटकर रुककर चुपकर कुर्ते पिरोकर चितरकर टकरकर पे के ते रे चे टे पेच केत रेत चेत पो को तो रो चो टो रोक कोट चोर पोत पो तो को रो चो टो कोट रोक चोर पोत पिरो किर तिको चितर पुटक कुरत चुपे रुकट पिरत पिटकर रुककर चुपकर कुर्ते पिरोकर चितरकर टकरकर चितर पुटक कुरत चुपे रुकट पिरत पिटकर रुककर चुपकर कुर्ते पिरोकर चितरकर टकरकर",
    4: "पिरोत कर्तक चित्तर पर्चे करते टकरो चुरोत रुकत पिटत करते पिरोत टकरो चुरोत रुकत पिटत कर्तक चित्तर पर कर तक पट टक चट कप पच रट टप पिर किर तिर चित चिप टिप तिक पिट चिर पुर कुर तुर चुर टुक पुट कुट तुक चुक रुक पुट कुट तुक चुक रुक पुर पेट रेट कोर्ट चोर टोक रोक कुर्तो पर्चो किरो चितो रुककर चुपकर कुर्ते पिरोकर चितरकर टकरकर चितर पुटक कुरत चुपे रुकट पिरत पिटकर",
    5: "पिरोकर कर्तको चित्तरक पर्चोकर करतेकरते टकरोकर चुरोकर रुककर पिटकर कुरते टकरोकर पिरोकर करतेकरते चुरोकर रुककर पिटकर कर्तको चित्तरक पर्चोकर करते पिरोत टकरो चुरोत रुकत पिटत कर्तक चित्तर पिरोत कर्तक चित्तर पर्चे करते टकरो चुरोत रुकत पिटत पेट रेट कोर्ट चोर टोक रोक कुर्तो पर्चो किरो चितो रेट पेट कोट रोक चोर टोक पर्चो कुरतो चितो किरो  चट कप पच रट टप पर कर तक पट टक चट कप पच रट टप कर पट टक चट कप पच रट टप पर तक कर पट टक चट कप पच रट टप पर तक",
    6: "पिरोकरते कर्तककर चित्तरकर पर्चोकरते करतेकरते टकरोकरते चुरोकरते रुककरते पिटकरते कुरतेकर करतेकरते पिरोकरते टकरोकरते चुरोकरते रुककरते पिटकर टकरोकर पिरोकर करतेकरते चुरोकर रुककर पिटकर कर्तको चित्तरक पर्चोकर पिरोकर कर्तको चित्तरक पर्चोकर करतेकरते टकरोकर चुरोकर रुककर पिटकर कुरते करते पिरोत टकरो चुरोत रुकत पिटत कर्तक चित्तर पिरोत कर्तक चित्तर पर्चे करते टकरो चुरोत रुकत पिटत रेट पेट कोट रोक चोर टोक पर्चो कुरतो चितो किरो पेट रेट कोर्ट चोर टोक रोक कुर्तो पर्चो किरो चितो पिरोत कर्तक चित्तर पर्चे करते टकरो चुरोत रुकत पिटत करते पे के ते रे चे टे पेच केत रेत चेत पो को तो रो चो टो रोक कोट चोर पोत पो तो को रो चो टो",





    1: `The rapid integration of technology into the Indian legal system has brought about a
significant transformation in how research is conducted and how judgments are prepared.
While the use of digital tools like the e-Courts mission and virtual hearings has increased
efficiency, the recent emergence of generative artificial intelligence (AI) has presented a
unique challenge to the sanctity of the legal process. A trending concern across various High
Courts is the phenomenon known as "AI Hallucination," where automated tools provide
references to non-existent judgments or "fake" case laws. This issue came to light recently
when several trial courts noticed that citations provided in the arguments of advocates could
not be found in any official law journal or digital database. The Hon'ble High Court of
Andhra Pradesh, in a significant observation, cautioned that while AI can be a helpful
assistant, it can never replace the human intellect and the moral reasoning of a judge. The
Court noted that legal research is not merely about finding a matching keyword; it is about
understanding the context, the ratio decidendi, and the evolution of legal principles over time.
AI systems, which work on probability and data patterns, often "hallucinate" information that
appears persuasive and authoritative but is factually incorrect. Relying on such non-existent
authorities violates the basic principles of "due process" and could lead to a serious
miscarriage of justice. It is the duty of every legal practitioner to verify each citation before
presenting it in the court of law. Furthermore, the debate around the "Digital Lawyer" and
"Digital Judiciary" suggests that the use of technology must be regulated by a strict "Ethical
Framework." Many law tribunals have started issuing guidelines for the use of AI in drafting
petitions and written submissions. The primary concern is that a lawyer might unknowingly
submit a document that contains errors generated by a machine, thereby misleading the court.
The "Bar Council of India" and other regulatory bodies are currently discussing the necessity
of a certification process for AI tools used in the legal field. The objective is to ensure that
the tools are "trained" on verified Indian statutes and actual judgments from the Supreme
Court and various High Courts, rather than unverified data from the internet. In a recent case,
a trial judge admitted to using an AI tool for the first time to assist in drafting a routine order.
Unfortunately, the tool provided four citations that were completely fictional. Although the
final decision was correct on its legal merits, the High Court had to step in to clarify that the
"actual intelligence" of the presiding officer must always prevail over "artificial intelligence." The Court emphasized that a judgment must be a "reasoned document" that reflects the
judicial mind. A machine lacks the capacity to appreciate human emotions, the nuances of a
witness's testimony, or the social impact of a particular verdict. The transition toward a
"Paperless Court" and "AI-assisted Research" is inevitable, but it must be accompanied by
"Digital Literacy" among advocates and judicial officers.`,
    2: ``,
    3: ``,
    4: ``,
    5: ``,
    6: ``,
    7: ``,
    8: ``,
    9: ``,
    10: ``,
    11: ``,
    12: ``,
    13: ``,





};

export const textSamples = {
    "easy": [
        "You know what I've noticed? Nobody panics when things go 'according to plan'. Even if the plan is horrifying. If, tomorrow, I tell the press that, like, a gang banger will get shot, or a truckload of soldiers will be blown up, nobody panics, because it's all 'part of the plan'. But when I say that one little old mayor will die, well then everyone loses their minds!",

        "I've always believed in numbers, in equations, in logic and reason.But after a lifetime of such pursuits: I ask What truly is logic? Who decides reason? My quest has taken me to the physical, the metaphysical, the delusional, and back.",

        "It’s the ship that made the Kessel run in less than twelve parsecs. I’ve outrun Imperial starships. Not the local bulk cruisers, mind you. I’m talking about the big Corellian ships, now. She’s fast enough for you, old man.",

        "Call me Ishmael. Some years ago - never mind how long precisely - having little or no money in my purse, and nothing particular to interest me on shore, I thought I would sail about a little and see the watery part of the world. It is a way I have of driving off the spleen and regulating the circulation.",

        "I don't know why he saved my life. Maybe in those last moments he loved life more than he ever had before. Not just his life - anybody's life; my life. All he'd wanted were the same answers the rest of us want. Where did I come from? Where am I going? How long have I got? All I could do was sit there and watch him die.",

        "I've seen things you people wouldn't believe. Attack ships on fire off the shoulder of Orion. I watched C-beams glitter in the dark near the Tannhauser gate. All those moments will be lost in time... like tears in rain... Time to die.",

        "This is your last chance. After this, there is no turning back. You take the blue pill, the story ends, you wake up in your bed and believe whatever you want to believe. You take the red pill, you stay in Wonderland and I show you how deep the rabbit-hole goes.",

        "A portion of the army that had retreated from Ticonderoga was camped on the flats near the town, and Robert and Tayoga walked swiftly toward the tents. It was a much more silent force, British and American, than that which had gone forth not so very long ago to what seemed certain victory. Officers and men were angry. They felt that they had been beaten when there was no reason why they should have been defeated. ",

        "He was the victim of a railway accident. He had gone to New York on business, and was expected back on a certain day. The train on which he was a passenger collided with a freight train, and my poor father was among the passengers who were killed. The news was almost too much for my poor mother, although she had not yet become an invalid.",

        "Text characteristics determine whether a text is easy or hard for a student to read. There is a degree of variation within each level. The challenge of one book might be figurative language, while the challenge of another book at the same level might be sentence length, vocabulary, or advanced concepts.",

        "Now it happened that Ben had not less than five dollars about him. He had carried some groceries to a remote part of the town, and collected two bills on the way. All this money he had in a wallet in the pocket on the other side from the tramp. But the money was not his. It belonged to his employer, and he was not disposed to give it up without a struggle, though he knew that in point of strength he was not an equal match for the man beside him.",

        "The storm in question, I regret to say, was brought about by the luckless Jack. As has been said, he was engaged in constructing a boat, the particular operation he was now intent upon being the excavation, or hollowing out. Now three-legged stools are not the most secure seats in the world. This, I think, no one will deny who has any practical acquaintance with them. ",
    ],
    "medium": [
        "The University of Oregon, also referred to as UO, U of O or Oregon, is a public flagship research university in Eugene, Oregon. Founded in 1876, the institution's 295-acre campus is along the Willamette River. Since July 2014, UO has been governed by the Board of Trustees of the University of Oregon. The university has a Carnegie Classification of 'highest research activity' and has 19 research centers and institutes. UO was admitted to the Association of American Universities in 1969.",

        "When the first digital computers appeared in the early 1940s, the instructions to make them operate were wired into the machine. Practitioners quickly realized that this design was not flexible and came up with the 'stored program architecture' or von Neumann architecture. Thus the division between 'hardware' and 'software' began with abstraction being used to deal with the complexity of computing.",

        "With respect Master Wayne, perhaps this is a man that you don't fully understand, either. A long time ago, I was in Burma. My friends and I were working for the local government. They were trying to buy the loyalty of tribal leaders by bribing them with precious stones. But their caravans were being raided in a forest north of Rangoon by a bandit. So, we went looking for the stones. But in six months, we never met anybody who traded with him. One day, I saw a child playing with a ruby the size of a tangerine. The bandit had been throwing them away.",

        "Don't talk like you're one of them! You're not, even if you'd like to be. To them you're just a freak, like me. They need you right now, but when they don't, they'll cast you out—like a leper. See, their morals, their 'code'…it's a bad joke, dropped at the first sign of trouble. They're only as good as the world allows them to be. I'll show you, when the chips are down, these-ah-'civilised people'? They'll eat each other. See, I'm not a monster. I'm just ahead of the curve.",

        "If we all go for the blonde and block each other, not a single one of us is going to get her. So then we go for her friends, but they will all give us the cold shoulder because no on likes to be second choice. But what if none of us goes for the blonde? We won't get in each other's way and we won't insult the other girls. It's the only way to win.",

        "See now I'm thinkin', maybe it means you're the evil man. And I'm the righteous man. And Mr. 9 Milimeter here, he's the shepherd protecting my righteous ass in the valley of darkness. Or it could mean you're the righteous man and I'm the shepherd and it's the world that's evil and selfish. Now I'd like that. But that shit ain't the truth. The truth is you're the weak. And I'm the tyranny of evil men. But I'm tryin', Ringo. I'm tryin' real hard to be a shepherd.",

        "Squire Newcome was a widower. His wife, who was as different from himself as could well be conceived, did not live long after marriage. She was chilled to death, as it was thought, by the dignified iceberg of whose establishment she had become a part. She had left, however, a child, who had now grown to be a boy of twelve. This boy was a thorn in the side of his father, who had endeavored in vain to mould him according to his idea of propriety.",

        "There is in each of us an ancient force that takes and an ancient force that gives. A man finds little difficulty facing that place within himself where the taking force dwells, but it’s almost impossible for him to see into the giving force without changing into something other than man. For a woman, the situation is reversed. ... These things are so ancient within us that they're ground into each separate cell of our bodies. We're shaped by such forces.",

        "I have made up my mind to go to Norway for three months. Principal object to chase the sun. Secondary objects, health and amusement. Will you go? You will find my schooner comfortable, my society charming (if you make yourself agreeable), and no end of salmon-fishing and scenery. Reply by return of post. I go to Hull to-morrow, and will be there a week. This will give you ample time to get ready.",

        "The thing the ecologically illiterate don’t realize about an ecosystem is that it’s a system. A system! A system maintains a certain fluid stability that can be destroyed by a misstep in just one niche. A system has order, a flowing from point to point. If something dams the flow, order collapses. The untrained might miss that collapse until it was too late. That’s why the highest function of ecology is the understanding of consequences.",

        "On the arrival of Lewis and Clarke at the mouth of the Columbia, in 1806, the new language, from the sentences given by them, had evidently attained some form. It was with the arrival of Astor's party, however, that the Jargon received its principal impulse. Many more words of English were then brought in, and for the first time the French, or rather the Canadian and Missouri patois of the French, was introduced.",
    ],
    "hard": [
        "A neutron star is the collapsed core of a large star which before collapse had a total of between 10 and 29 solar masses. Neutron stars are the smallest and densest stars, not counting hypothetical quark stars and strange stars. Typically, neutron stars have a radius on the order of 10 kilometres and a mass between 1.4 and 3 solar masses. They result from the supernova explosion of a massive star, combined with gravitational collapse, that compresses the core past the white dwarf star density to that of atomic nuclei.",

        "Tonight you're all gonna be part of a social experiment. Through the magic of diesel fuel and ammonium nitrate, I'm ready right now to blow you all sky high. Anyone attempts to get off their boat, you all die. Each of you has a remote... to blow up the other boat. At midnight, I blow you all up. If, however, one of you presses the button, I'll let that boat live. So, who's it going to be: Harvey Dent's most wanted scumbag collection, or the sweet and innocent civilians? You choose... oh, and you might want to decide quickly, because the people on the other boat might not be so noble.",

        "Ya wanna know how I got these scars? My father; was a drinker; and a fiend. And one night, he goes off crazier than usual. Mommy grabs the kitchen knife to defend herself. He doesn't like that. Not. One. Bit. So, me watching, he takes the knife to her, laughing while he does it. He turns to me and say, why so serious? He comes at me with the knife. Why so serious? Sticks the blade in my mouth. Let's put a smile on that face! Aaaaaand. Why so serious?",

        "Mathematicians won the war. Mathematicians broke the Japanese codes... and built the A-bomb. Mathematicians... like you. The stated goal of the Soviets is global Communism. In medicine or economics, in technology or space, battle lines are being drawn. To triumph, we need results. Publishable, applicable results. Now who among you will be the next Morse? The next Einstein? Who among you will be the vanguard of democracy, freedom, and discovery? Today, we bequeath America's future into your able hands.",

        "Well, Prince, Genoa and Lucca are now no more than private estates of the Bonaparte family. No, I warn you, that if you do not tell me we are at war, if you again allow yourself to palliate all the infamies and atrocities of this Antichrist (upon my word, I believe he is), I don't know you in future, you are no longer my friend, no longer my faithful slave, as you say. There, how do you do, how do you do? I see I'm scaring you, sit down and talk to me.",

        "Have you ever stood and stared at it, marveled at its beauty, its genius? Billions of people just living out their lives, oblivious. Did you know that the first Matrix was designed to be a perfect human world, where none suffered, where everyone would be happy? It was a disaster. No one would accept the program, entire crops were lost. Some believed we lacked the programming language to describe your perfect world, but I believe that, as a species, human beings define their reality through misery and suffering.",

        "I'd like to share a revelation that I've had during my time here. It came to me when I tried to classify your species and I realized that you're not actually mammals. Every mammal on this planet instinctively develops a natural equilibrium with the surrounding environment but you humans do not. You move to an area and you multiply and multiply until every natural resource is consumed and the only way you can survive is to spread to another area. There is another organism on this planet that follows the same pattern. Do you know what it is? A virus. Human beings are a disease, a cancer of this planet. You're a plague and we are the cure.",

        "Well there's this passage I got memorized. Ezekiel 25:17. 'The path of the righteous man is beset on all sides by the inequities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of the darkness. For he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who attempt to poison and destroy my brothers. And you will know I am the Lord when I lay my vengeance upon you.'",

        "Mr. Bingley was good-looking and gentlemanlike; he had a pleasedasant countenance, and easy, unaffected manners. His sisters were fine women, with an air of decided fashion. His brother-in-law, Mr. Hurst, merely looked the gentleman; but his friend Mr. Darcy soon drew the attention of the room by his fine, tall person, handsome features, noble mien, and the report which was in general circulation within five minutes after his entrance, of his having ten thousand a year.",

        "The different accidents of life are not so changeable as the feelings of human nature. I had worked hard for nearly two years, for the sole purpose of infusing life into an inanimate body. For this I had deprived myself of rest and health. I had desired it with an ardour that far exceeded moderation; but now that I had finished, the beauty of the dream vanished, and breathless horror and disgust filled my heart. Unable to endure the aspect of the being I had created, I rushed out of the room and continued a long time traversing my bed-chamber, unable to compose my mind to sleep.",

        "One should always keep in mind that psychology is essentially a laboratory science, and not a text-book subject. The laboratory material is to be found in ourselves and in those about us. While the text should be thoroughly mastered, its statements should always be verified by reference to one's own experience, and observation of others. Especially should prospective teachers constantly correlate the lessons of the book with the observation of children at work in the school. The problems suggested for observation and introspection will, if mastered, do much to render practical and helpful the truths of psychology.",

        "He then leaves the abode of filth and intemperance, and squalid poverty, and ill-temper, for a clean, airy place, pleasant in summer, warm and dry in winter; and where he sees not a face that is not lighted up with the smile of kindness towards him. His whole day is passed in amusing exercises, or interesting instruction; and he returns at evening-tide fatigued and ready for his bed, so that the scenes passing at his comfortless home make a slight impression on his mind or on his spirits."
    ]
}